name: OSV Scanner

on:
  pull_request:
  merge_group:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  osv-scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.6.0
    permissions:
      actions: read
      contents: read
      security-events: write
